---
title: CASTOR Software Days
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://castor-software-days-2019.github.io/
baseurl: "/"
email: sw-days-organizers@kth.se
description: ''
organization:
- name: Benoit Baudry
  pic: benoit
  position: General co-chair and DevOps track co-chair
  social:
  - title: globe
    url: https://softwarediversity.eu
  - title: envelope
    url: mailto:baudry@kth.se
- name: Frédéric Loiret
  pic: frederic
  position: General co-chair and DevOps track co-chair
  social:
  - title: globe
    url: http://www.scanx.org/loiret/
  - title: envelope
    url: mailto:floiret@kth.se
- name: Amir H. Payberah
  pic: amir
  position: Distributed systems track co-chair
  social:
  - title: globe
    url: https://payberah.github.io/
  - title: envelope
    url: mailto:payberah@kth.se
- name: Musard Balliu
  pic: musard
  position: Safety and security track co-chair
  social:
  - title: globe
    url: https://www.csc.kth.se/~musard/
  - title: envelope
    url: mailto:musard@kth.se
- name: Cyrille Artho
  pic: cyrille
  position: Safety and security track co-chair
  social:
  - title: globe
    url: https://people.kth.se/~artho/
  - title: envelope
    url: mailto:artho@kth.se
- name: Philipp Haller
  pic: philipp
  position: Distributed systems track co-chair
  social:
  - title: globe
    url: http://www.csc.kth.se/~phaller/
  - title: envelope
    url: mailto:phaller@kth.se
- name: Maria Berthelius
  pic: maria
  position: Local organizer
  social:
  - title: globe
    url: https://www.kth.se/profile/berthel
  - title: envelope
    url: mailto:berthel@kth.se
- name: Alexandra Leyton
  pic: alexandra
  position: Student liaison and communication
  social:
  - title: globe
    url: https://www.kth.se/profile/aleyton
  - title: envelope
    url: mailto:aleyton@kth.se
- name: Oscar Luis Vera-Pérez
  pic: oscar
  position: Web consultant
  social:
  - title: globe
    url: https://www.linkedin.com/in/oscar-luis-vera-p%C3%A9rez-608392125
  - title: envelope
    url: mailto:oscar.vera-perez@inria.fr
speakers_devops:
- name: Daniel Stenberg
  pic: daniel
  position: The author and maintainer of cURL and libcurl
  social:
  - title: globe
    url: https://daniel.haxx.se/
- name: Martin Monperrus
  pic: martin
  position: Professor of theoretical computer science at KTH
  social:
  - title: globe
    url: https://www.kth.se/profile/monp
- name: Philipp Haller
  pic: philipp
  position: Associate professor of theoretical computer science at KTH
  social:
  - title: globe
    url: http://www.csc.kth.se/~phaller/
- name: TBA
  pic: tba
  position: TBA
  social:
  - title: globe
    url: 
speakers_security:
- name: David Basin
  pic: david
  position: Professor of computer science at ETH Zurich
  social:
  - title: globe
    url: http://people.inf.ethz.ch/basin/
- name: Andrei Sabelfeld
  pic: andrei
  position: Professor of computer science at Chalmers
  social:
  - title: globe
    url: http://www.cse.chalmers.se/~andrei/
- name: Pontus Johnson
  pic: pontus
  position: Professor of cyber security at KTH
  social:
  - title: globe
    url: https://www.kth.se/profile/pontusj
- name: TBA
  pic: tba
  position: TBA
  social:
  - title: globe
    url: 
speakers_ds:
- name: Peter Pietzuch
  pic: peter
  position: Professor in the Department of Computing at Imperial College London
  social:
  - title: globe
    url: https://www.doc.ic.ac.uk/~prp/
- name: Jim Dowling
  pic: jim
  position: Associate professor of computer systems at KTH
  social:
  - title: globe
    url: https://www.kth.se/profile/jdowling
- name: Leila Bahri
  pic: leila
  position: Postdoc researcher of computer systems at KTH
  social:
  - title: globe
    url: https://www.kth.se/profile/lbahri
- name: Amir H. Payberah
  pic: amir
  position: Assistant professor of computer systems at KTH
  social:
  - title: globe
    url: https://payberah.github.io/
social:
- title: envelope
  url: mailto:sw-days-organizers@kth.se
- title: globe
  url: https://www.castor.kth.se
- title: twitter
  url: https://twitter.com/CastorKth
